### ISSUE TITLE
Add readme file

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#24]
The current readme is a bit basic improving it would make it easier for new contributors to look at it and run the project for themselves!

**Comment by ayushmankoley** [comment]
Hey would love to contribute please assign

**Comment by mezotv** [comment]
> Hey would love to contribute please assign

Sure sounds good!

**Comment by ayushmankoley** [comment]
@mezotv Updated, do add the necessary tags and merge it ty
