### ISSUE TITLE
Create Docker image

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#25]
Build the website as a docker image and deploy that to a vps/vds for automatic deployment.

**Comment by GopalVerma1303** [comment]
Hey 👋. Can I take this issue on? I'm happy to build and deploy the website as a Docker image to a VPS/VDS for automatic deployment.

**Comment by mezotv** [comment]
> Hey 👋. Can I take this issue on? I'm happy to build and deploy the website as a Docker image to a VPS/VDS for automatic deployment.

Sure I will assign this to you!

**Comment by GopalVerma1303** [comment]
PR #41 is resolving this issue.
