### ISSUE TITLE
Add /games pages

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#27]
Add a dedicated page for each game mode like the ones below.

- /wouldyourather
- /higherorlower
- /whatwouldyoudo
- /neverhaveIever

All of them would be in a folder called games so the url ends up being /games/wouldyourather.

**Comment by Ayushpanditmoto** [comment]
assign me this

**Comment by mezotv** [comment]
> assign me this 

Hey sure! If you have questions about the design whatsoever please let me know!

**Comment by Ayushpanditmoto** [comment]
can you explain ?? you want yourwebsite/game/wouldyourather or yourwebsite/wouldyourather

**Comment by mezotv** [comment]
> can you explain ?? you want yourwebsite/game/wouldyourather or yourwebsite/wouldyourather

We want websitemcom/games/wouldyourather etc etc
