### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#28]
Add a code of conduct so new contributors know what to do and what not.

**Comment by Ayushpanditmoto** [comment]
Assign me /assign

**Comment by mezotv** [comment]
> Assign me /assign

Sure will do!

**Comment by Ayushpanditmoto** [comment]
@mezotv code of conduct already there bro

**Comment by mezotv** [comment]
> @mezotv code of conduct already there bro

Oh yea your right. I didn't see that sorry!
