### ISSUE TITLE
Add pr/issue template

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#29]
Add an issue and pr template so contributors are required to folllow a predefined style for their pull requests and issues.

**Comment by Shikhar02347893** [comment]
hi @mezotv can you please assign this to me

**Comment by mezotv** [comment]
> hi @mezotv can you please assign this to me
> 

Sure will do!

**Comment by Petsamuel** [comment]
please can you assign this to me?
I have a deep knowledge about GitHub workflows.
