### ISSUE TITLE
Add reading progress bar

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#30]
Add a reading progress bar for the blog pages to show how much content there is left.

Similar to this screenshot ![hubspot-progress-bar.jpg](https://github.com/Would-You-Bot/website/assets/68947960/4c77e310-b025-4f6e-ab28-ddd23206f900)

But with matching colors ofc!

**Comment by AksBad007** [comment]
Hi! could you assign this to me plz?

**Comment by mezotv** [comment]
> Hi! could you assign this to me plz?

Sure there you go!
