### ISSUE TITLE
Fix mobile blog view

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#38]
Fix the mobile blog view where tags and text overflows like this:

![Screenshot_20231002_094046_Chrome.jpg](https://github.com/Would-You-Bot/website/assets/68947960/ec24e6b5-3174-40cd-9042-8468dc13f1c5)

**Comment by luckyklyist** [comment]
Can you assign these issues to me? I will be happy to work on this.

**Comment by mezotv** [comment]
> Can you assign these issues to me? I will be happy to work on this.
> 

Sure thing will do!
