### ISSUE TITLE
Blog tags are to big

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#39]
When a blog tag is to long the box around it gets to big ![image-68.png](https://github.com/Would-You-Bot/website/assets/68947960/da08c030-a413-46dd-bdfa-dac5231ee62f)

Fix this by displaying ... when a tag is zo long.

**Comment by joshijoe05** [comment]
Hello i would like to work on this issue please assign this to me

**Comment by mezotv** [comment]
> Hello i would like to work on this issue please assign this to me 

Sure there you go!

**Comment by joshijoe05** [comment]
Can you guide where the issue was?

**Comment by mezotv** [comment]
> Can you guide where the issue was?

It happends when creating a new blog and giving the post a really long tag along with sole normal sized ones

**Comment by joshijoe05** [comment]
Give the steps to reproduce it, I cannot find the issue

**Comment by mezotv** [comment]
> Give the steps to reproduce it, I cannot find the issue

Seems like someone else fixed it.

**Comment by joshijoe05** [comment]
Yes might be, the issue is not there !
