### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#49]
Add a pull request template asking the user to check boxes where they confirm the code works at least on their machine and that they have modified the build steps if changed. In addition to that also allow the user to add a list of changes they have made!

**Comment by ujwalkumar1995** [comment]
Hey @mezotv 
I would like to work on this.
Could you please assign?

**Comment by mezotv** [comment]
> Hey @mezotv 
> I would like to work on this.
> Could you please assign?

Sure there you go!
