### ISSUE TITLE
Add issues/pr labels

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#56]
Add a label workflow similar to the one used here https://github.com/EddieHubCommunity/BioDrop/blob/main/.github/workflows/labels.yml

Make sure to modify to fit this repos needs!

**Comment by Petsamuel** [comment]
Assign to me

**Comment by ArslanYM** [comment]
Can I work on this?

**Comment by mezotv** [comment]
> Can I work on this?

You sure can!

**Comment by ArslanYM** [comment]
@mezotv Can you specify the needs of this project.

**Comment by mezotv** [comment]
> @mezotv Can you specify the needs of this project.

Well we want it to be easy for new open source contributors to find issues that fit for them. We would also like issue tags for updating certain features of the website.
