### ISSUE TITLE
Add automatic release

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#57]
Add a workflow to automatically publish a new release and increment the number similar to this one https://github.com/EddieHubCommunity/BioDrop/blob/main/.github/workflows/release.yml

**Comment by GopalVerma1303** [comment]
Hey! Could you please assign this issue to me? Ig it aligns with the work I'm currently doing. Thanks!

**Comment by Siddharth9890** [comment]
hey @mezotv can i work on this?

**Comment by mezotv** [comment]
> hey @mezotv can i work on this?

Sure you can!

**Comment by mezotv** [comment]
Hey @Siddharth9890, how is it going so far?

**Comment by Siddharth9890** [comment]
hey @mezotv i have not started it yet but will start during the weekend

**Comment by mezotv** [comment]
> hey @mezotv i have not started it yet but will start during the weekend. But basically we need something very similar to file you shared right?

Basically yea
