### ISSUE TITLE
Upgrade readme

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#58]
Upgrade the readme to add a screenshot of the site, how to run the project and add more information into the readme to make it look better. This should be fairly advanced for it to not count as a spam pr.

Be creative with it too!

**Comment by jfmartinz** [comment]
can you please assign this issue to me?

**Comment by mezotv** [comment]
> can you please assign this issue to me? 

Sure!

**Comment by jfmartinz** [comment]
@mezotv
