### ISSUE TITLE
[REQUEST] - Copy command on click

### ISSUE THREAD

**Issue by mezotv** [Would-You-Bot/website#60]
### Description

On the https://wouldyoubot.gg/commands page allow the user to click the usage command and copy it to their clipboard. 

You could change the text of the command to --Click to copy-- when hovering over it and drag down the opacity of the text a bit. And then copy once clicked you copy the command to the users clipboard!

**Comment by Honey2339** [comment]
Interesting. I would like to work on this.

**Comment by mezotv** [comment]
> Interesting. I would like to work on this.

Sure sounds good!

**Comment by Honey2339** [comment]
Hey! i wanna know that do we need a Toast/Notification when someone clicks on the "--Click To Copy--"

**Comment by mezotv** [comment]
> Hey! i wanna know that do we need a Toast/Notification when someone clicks on the "--Click To Copy--". If yes then can i add react-toastify to project library?

I think changing the text to a sucess message should do the job. After the user stops hovering it should go back to the original

**Comment by Honey2339** [comment]
Please review the above PR. 
Thanks!
