### ISSUE TITLE
Support Server Links (Button at top right of page and hyperlink in Footer) lead to a 404.

### ISSUE THREAD

**Issue by AustinHolderr** [Would-You-Bot/website#9]
## Short Description:
Support Server Links (Button at top right of page and hyperlink in Footer) lead to a 404.

## Steps to Reproduce:
- Go to https://wouldyoubot.gg/
- Click "Support" at the top right of the page, or "Support Server" in the Footer
- Notice how it leads to a 404 page.

## Expected Behavior:
No 404, leads to Discord Invite Link.

## Actual Behavior:
404 page.

**Comment by mezotv** [comment]
Thanks for pointing this out I have gone ahead and fixed this!
